package com.teaonlinestore.model;
// default package
// Generated 11 лист. 2015 17:29:02 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AttributeValueDouble generated by hbm2java
 */
@Entity
@Table(name = "attributevaluedouble", schema = "public")
public class AttributeValueDouble implements java.io.Serializable {
	@Id
	@Column(name = "attribute_value_double_id", nullable = false)
	@GeneratedValue(strategy = GenerationType.AUTO)
	private long attributeValueDoubleId;
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "attribute_id", nullable = false)
	private Attribute attribute;
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_id")
	private Product product;
	@Column(name = "value", nullable = false)
	private double value;

	public AttributeValueDouble() {
	}

	public AttributeValueDouble(long attributeValueDoubleId,
			Attribute attribute, double value) {
		this.attributeValueDoubleId = attributeValueDoubleId;
		this.attribute = attribute;
		this.value = value;
	}

	public AttributeValueDouble(long attributeValueDoubleId,
			Attribute attribute, Product product, double value) {
		this.attributeValueDoubleId = attributeValueDoubleId;
		this.attribute = attribute;
		this.product = product;
		this.value = value;
	}

	
	public long getAttributeValueDecimal() {
		return this.attributeValueDoubleId;
	}

	public void setAttributeValueDecimal(long attributeValueDoubleId) {
		this.attributeValueDoubleId = attributeValueDoubleId;
	}

	public Attribute getAttribute() {
		return this.attribute;
	}

	public void setAttribute(Attribute attribute) {
		this.attribute = attribute;
	}

	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	public double getValue() {
		return this.value;
	}

	public void setValue(double value) {
		this.value = value;
	}

}
