package com.teaonlinestore.model;
// default package
// Generated 11 лист. 2015 17:29:02 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PurchaseproductId generated by hbm2java
 */
@Embeddable
public class PurchaseProductId implements java.io.Serializable {
	@Column(name = "product_id", nullable = false)
	private long productId;
	@Column(name = "purchase_id", nullable = false)
	private long purchaseId;

	public PurchaseProductId() {
	}

	public PurchaseProductId(long productId, long purchaseId) {
		this.productId = productId;
		this.purchaseId = purchaseId;
	}

	public long getProductId() {
		return this.productId;
	}

	public void setProductId(long productId) {
		this.productId = productId;
	}

	
	public long getPurchaseId() {
		return this.purchaseId;
	}

	public void setPurchaseId(long purchaseId) {
		this.purchaseId = purchaseId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PurchaseProductId))
			return false;
		PurchaseProductId castOther = (PurchaseProductId) other;

		return (this.getProductId() == castOther.getProductId())
				&& (this.getPurchaseId() == castOther.getPurchaseId());
	}

	public int hashCode() {
		int result = 17;
		result = 37 * result + (int) this.getProductId();
		result = 37 * result + (int) this.getPurchaseId();
		return result;
	}

}
